---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: ge-metrics-discovery
  name: ge-metrics-discovery
  namespace: gem
spec:
  clusterIP: None
  ports:
    - name: ge-metrics-grpc
      port: 9095
      targetPort: 9095
    - name: ge-metrics-gossip
      port: 7946
      targetPort: 7946
  publishNotReadyAddresses: true
  selector:
    name: ge-metrics
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: ge-metrics
  name: ge-metrics
  namespace: gem
spec:
  ports:
    - name: ge-metrics-http-metrics
      port: 8000
      targetPort: http-metrics
  selector:
    name: ge-metrics
  sessionAffinity: None
  type: LoadBalancer
